### ISSUE TITLE
vendors

### ISSUE THREAD

**Issue by AntonioValerioCalo** [AntonioValerioCalo/progetto-spotify#6]
1.Creare una cartella Artisti ed inserire il file vendors.html all'interno.
2. Cancellare il file index.html vuoto dal branch features/vendors.
3. Aggiunger immagini.
4. riga 25 e 26 togliere il collegamento con il sito originali lì va messo il collegamento con le nostre pagine create.
5. Aggiungere il il favicon.
6.Aggiungere i meta og: .

**Comment by Enriko35** [comment]
Checked and delivered
